resources:
- name: terraform-resource
  type: git
  source:
    uri: https://github.com/KomaNelson/terraform-test.git
    branch: master

jobs:
- name: job-terraform-s3-bucket
  plan:
  - get: terraform-resource
    trigger: true
  - task: terraform-s3
    file: terraform-resource/build/build.yml
    params:
      aws_ID: ((aws_access_key))
      aws_KEY: ((aws_secret_key))
      aws_Region: ((aws_region))
    
- name: plan-terraform
  plan:
   - get: terraform-resource
   - task: terraform
     config:
       platform: linux
       image: 
       inputs:
        - name: terra-output
     run: 
       path: sh
       args:
        - -exc
        - |
          cd terraform-resource/main/
          terraform plan
