resources:
- name: terraform-resource
  type: git
  source:
    uri: https://github.com/KomaNelson/terraform-test.git
    branch: master

jobs:
- name: create-s3-bucket
  plan:
  - get: terraform-resource
    trigger: true
  - task: install-terraform
    file: terraform-resource/build/install_terraform.yml
    params:
      aws_ID: ((aws_access_key))
      aws_KEY: ((aws_secret_key))
      aws_Region: ((aws_region))
  - task: terraform-prepare
    file: terraform-resource/build/terraform_prepare.yml
